micronaut:
  application:
    name: kasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:kasa_do_codigo_db}?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jpa.default.properties.hibernate.hbm2ddl.auto: update

##
# Jackson configuration
# https://github.com/micronaut-projects/micronaut-core/issues/240
# https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/
# https://www.baeldung.com/jackson-serialize-dates
##
jackson:
  serialization:
    writeDatesAsTimestamps: false
